### ISSUE TITLE
Work plan

### ISSUE THREAD

**Issue by ramess101** [ramess101/IFPSC_10#9]
This is a list of the simulations we need to run

Put a * next to high priority tasks
Put your initials next to a task that you are currently working on

# Saturation viscosity

# New list of compounds

### C12H26

- [x] Potoff (SMR: done)

- [x] TraPPE
 
- [x] TAMie

### C16H34 (not working)

- [ ] Potoff

- [ ] TraPPE
 
- [ ] TAMie

### C22H46

- [ ] Potoff

- [ ] TraPPE (SMR: running)
 
- [ ] TAMie

### 22DM-butane (probably won't run this)

- [ ] Potoff

- [ ] TraPPE

### 23DM-butane

- [x] Potoff

- [x] TraPPE
 
- [x] TAMie

### 3-methylpentane

- [x] Potoff

- [x] TraPPE
 
- [x] TAMie

# Old list of compounds

### C2H6

- [ ] Potoff

- [ ] TraPPE
 
- [x] TAMie

- [ ] Exp-6

- [x] TraPPE-2

- [ ] MCMC 12-6

- [x] MCMC 13-6

- [x] MCMC 14-6

- [x] MCMC 15-6

- [x] MCMC 16-6

### C3H8

- [x] Potoff

- [x] TraPPE
 
- [x] TAMie

- [ ] Exp-6

- [x] MCMC 14-6 (low priority)

- [x] MCMC 16-6

### C4H10

- [x] Potoff

- [x] TraPPE
 
- [x] TAMie

- [ ] Exp-6

- [ ] MCMC 14-6 (low priority)

- [x] MCMC 16-6

### C8H18

- [x] Potoff

- [x] TraPPE
 
- [x] TAMie

- [ ] Exp-6

- [ ] MCMC 14-6 (low priority)

- [ ] MCMC 16-6

### IC4H10

- [x] Potoff

- [x] TraPPE
 
- [x] TAMie (SMR: Results are very similar to TraPPE)

- [x] AUA4

### IC5H12

- [x] Potoff 

- [x] TraPPE
 
- [x] TAMie

### IC6H14

- [x] Potoff (SMR: Done. Ran again due to wrong previous Potoff parameters for IC6)

- [x] TraPPE
 
- [x] TAMie

### IC8H18

- [x] Potoff

- [x] TraPPE

### NEOC5H12

- [x] Potoff

- [x] TraPPE
 
- [x] AUA4

# Finite size effects

### C3H8, Potoff: 
- [x] N100 
- [x] N200
- [x] N400
- [x] N800

### C4H10, Potoff:

- [x] N100
- [x] N200 
- [x] N400
- [x] N800 

### C4H10, TraPPE:

- [x] N200
- [x] N400
- [x] N800 

### C8H18, TraPPE:

- [x] N200
- [x] N400
- [x] N800 

### IC8H18, TraPPE:

- [x] N200
- [x] N400
- [x] N800

# Simulation length

## Saturation

- [x] 0.5 ns
- [x] 1 ns
- [x] 2 ns
- [x] 4 ns

## High pressure

- [x] 1 ns
- [x] 2 ns 
- [x] 4 ns 

# Harmonic bonds

### TraPPE, N400

- [x] C3H8

- [x] C4H10

- [x] C8H18

# High pressure

### TraPPE, N400

- [x] C3H8 

- [x] C4H10

- [x] C8H18

- [x] IC5H12

- [ ] 3MPentane (SMR: Running)

### Potoff, N400

- [x] C3H8

- [x] C4H10

- [x] C8H18

### TAMie, N400 (high priority)

- [x] C3H8

- [x] C4H10

- [x] C8H18 

### MCMC Mie 16-6, N400

- [x] C3H8

- [ ] C4H10

- [ ] C8H18

### MCMC Mie 14-6, N400

- [ ] C3H8

- [ ] C4H10

- [ ] C8H18

### TraPPE, N400, C8H18 (Validation)

- [x] Harmonic

- [x] LINCS

**Comment by ramess101** [comment]
@mostafa-razavi 

The previous comment was for simulations. This list is for scripts that need to be written or modified.

# Shell scripts

- [x] Harmonic bonds

- [ ] Variable simulation length

- [ ] Include exponential-6

- [ ] Use different directory hierarchy when not using MCMC

- [ ] General branched alkanes script with harmonic bonds and/or finite size effects

- [ ] Separate force field script to improve readability

# Python scripts

### GreenKubo_analyze

- [x] Improve fit for high viscosity

- [x] More robust uncertainty quantification

- [x] Fit standard deviation to model

- [x] Speed-up uncertainty analysis 

- [x] Compare multiple force fields on same plot

- [x] Use Maginn's heuristic for determining tcut

### Pre-simulation files

- [x] Creates initial simulation conditions from REFPROP

**Comment by ramess101** [comment]
### SURF Student (Michelle Anderson, @Kaiveria ) Tasks

Short-term:

1. Walk through code with me:

    - [x] Saturated viscosity scripts
    - [x] Gromacs input files
    - [x] Pre-simulation python
    - [x] Post-simulation python

2. Walk through work plan

    - [x] Recap what has already been done
    - [x] Talk about what needs to still be done

3. Get set up to run jobs:

    - [x] Get access to calc1, md1
    - [x] Clone GitHub repository

4. Figure out dihedrals:

    - [x] Validate that we are implementing alkane dihedrals correctly

    - [ ] Determine how to implement the AUA4m dihedral model (very low priority now)

5. Validate n-octane TraPPE results from literature

    - [x] NVT ensemble only

       - [x] Simulate fixed bonds

       - [x] Simulate harmonic bonds

    - [x] NPT followed by NVT

        - [x] Simulate fixed bonds

        - [x] Simulate harmonic bonds

6. NPT ensemble

    - [x] Include NPT equilibration and production steps

    - [x] Determine which barostat to use and other parameters

    - [x] From average density, create new box for NVT ensemble

- [x] 7. Make branchedAlkane simulations more robust

- [x] 8. Pull REFPROP values for higher pressures (T293highP)

- [x] 9. Create T293highP conditions files for each molecule

- [x] 10. Reanalyze (GreenKubo_analyze.py) the state points where the uncertainties are inordinately large

- [x] 11. Modify T293highP script so that it includes NPT first

- [x] 12. Include RDF computation for high pressure runs

- [x] 13. Simulate isooctane at high pressures at 293 K (check that script works on md1)

- [x] 14. Move beyond Berendsen barostat

- [x] 15. Modify branchedAlkanes_SaturatedViscosity so that restarts whenever gromacs returns error

- [x] 16. Create .top and .gro files for challenge compound

- [x] 17. Create .top and .gro files for additional branched alkanes similar to challenge compound, i.e. 2,2,5-trimethylhexane, 2,4,4-trimethylhexane

- [x] 18. Extract TDE data and correlations for 2,2,4-trimethylhexane, 2,2,5-trimethylhexane, 2,4,4-trimethylhexane

- [x] 19. Create exponential-6 directory and files

- [x] 20. Allow for variable simulation time lengths, or at least longer simulations at higher pressures

- [ ] 21. Create generalized script

- [ ] 22. Saturation conditions at lower temperatures (i.e. near triple point), see propane for example

- [ ] 23. **Run nOctane, T347highP, TraPPE, harmonic, with NPT first on calc1** (make sure NPT production uses correct thermostat, barostat and taup)

- [x] 24. **Run IC4H10, T293highP, TraPPE, LINCS, NPT first on md1** (make sure NPT production uses correct thermostat, barostat and taup)

- [x] 25. **Run IC8H18, T293highP, Potoff, LINCS, NPT first, 4 ns on md1** (make sure NPT production uses correct thermostat, barostat and taup) we need be able to set the nsteps in NVT_vis. I would use 1 ns for the lowest pressure, 2 ns for the next two pressures, and 4 ns for the top two pressures.  

- [x] 26. **Repeat 24. and 25.** but with the different force fields. IC4H10 can do TraPPE, Potoff, TAMie, and AUA4. IC8H18 will just have TraPPE and Potoff.

Long-term:

- [ ] Finish running saturation jobs

- [ ] Start running high pressure simulations

- [ ] Nonequilibrium molecular dynamics (NEMD)

- [x] Test simulation length
